[project]
name = "boem"
description = "BOEM bird detection and classification pipeline"
readme = "README.md"
requires-python = ">=3.10"
version = "0.0.0"
dependencies = [
  "numpy",
  "pandas",
  "scikit-learn",
  "hydra-core",
  "omegaconf",
  "geopandas",
  "rasterio",
  "dask",
  "bokeh",
  "matplotlib",
  "paramiko",
  "torch",
  "torchmetrics",
  "pytorch-lightning",
  "label-studio-sdk",
  "label-studio-converter",
  "comet-ml",
  "deepforest",
  "globus-sdk",
  # H-CAST requirements
  "timm==0.4.12",
  "opencv-contrib-python==4.9.0.80",
  # DGL wheels may require a custom index (see https://data.dgl.ai/wheels/repo.html)
  "dgl",
  "packaging",
  "pytest",
  "python-dotenv>=1.2.1",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128" }
]
torchvision = [
  { index = "pytorch-cu128" }
]
deepforest = [
  { path = "/home/b.weinstein/DeepForest" }
]

[tool.uv]
find-links = ["https://data.dgl.ai/wheels/repo.html"]
